[package]
name = "trakt_api"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cache.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
utils.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.19.1"
tokio.workspace = true

[lints]
workspace = true
