[package]
name = "tmdb-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
emos-http.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
