name: tmdb_scifi.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  WATCH_ID: ${{ secrets.WATCH_ID }}
  DOUBAN_USER_ID: ${{ secrets.DOUBAN_USER_ID }}

  EMOS_TOKEN: ${{ secrets.EMOS_TOKEN }}
  EMOS_API_URL: ${{ secrets.EMOS_API_URL }}
  TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
  BANGUMI_ACCESS_TOKEN: ${{ secrets.BANGUMI_ACCESS_TOKEN }}

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run tmdb_scifi_media
        uses: ./.github/actions/task
        with:
          binary_name: "emos"
          task_args: "tmdb_scifi_media"

      - name: Run watch_hot_and_persistent
        uses: ./.github/actions/task
        with:
          binary_name: "emos"
          task_args: "watch_hot_and_persistent"

      - name: Upload json
        uses: ./.github/actions/upload
        with:
          CLOUDFLARE_R2_ACCOUNTID: ${{ secrets.CLOUDFLARE_R2_ACCOUNTID }}
          CLOUDFLARE_R2_KEY: ${{ secrets.CLOUDFLARE_R2_KEY }}
          CLOUDFLARE_R2_SECRET: ${{ secrets.CLOUDFLARE_R2_SECRET }}

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "20685961+bxb100@users.noreply.github.com"
          git add .
          git commit -m 'CI: generated'
          git push
