name: weekly_cover_generator.yml

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

env:
  EMOS_TOKEN: ${{ secrets.EMOS_TOKEN }}
  EMOS_API_URL: ${{ secrets.EMOS_API_URL }}
  TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
  BANGUMI_ACCESS_TOKEN: ${{ secrets.BANGUMI_ACCESS_TOKEN }}

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Generate scifi imgs
        uses: ./.github/actions/task
        with:
          binary_name: "emos"
          task_args: "tmdb_scifi_media --flag"
          token: ${{ github.token }}

      - name: Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: lib/cover_generator

      - name: Run script
        working-directory: lib/cover_generator
        run: |
          uv run main.py 'scifi' '科幻' 'Sci-fi'

      - uses: bxb100/.github/.github/actions/commit@main
        with:
          message: "chore: auto update"
